# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
    DuelsUpdateLeaderboardQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: duels-update-leaderboard
            VisibilityTimeout: 601
    DuelsUpdateLeaderboardQueuePolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
            PolicyDocument:
                Version: '2012-10-17'
                Id: DuelsUpdateLeaderboardQueuePolicy
                Statement:
                    - Sid: Allow-SNS-SendMessage
                      Effect: Allow
                      Principal:
                          AWS: '*'
                      Action:
                          - sqs:SendMessage
                      Resource: !GetAtt DuelsUpdateLeaderboardQueue.Arn
                      Condition:
                          ArnEquals:
                              aws:SourceArn: arn:aws:sns:us-west-2:478062583808:duels-review-published
            Queues:
                - !Ref DuelsUpdateLeaderboardQueue
    SnsSubscription:
        Type: AWS::SNS::Subscription
        Properties:
            Protocol: SQS
            Endpoint: !GetAtt DuelsUpdateLeaderboardQueue.Arn
            TopicArn: arn:aws:sns:us-west-2:478062583808:duels-review-published
    RetrieveDuelsLeaderboardFunction2:
        Type: AWS::Serverless::Function
        Properties:
            Handler: retrieve-duels-leaderboard.default
            Runtime: nodejs18.x
            CodeUri: ./dist/retrieve-duels-leaderboard
            Timeout: 29
            # Layers:
            #     - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-retrieve-duels-leaderboard-2
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE
